[package]
name = "guessing_game_tarik_learning"
version = "0.1.0"
authors = ["Tarik <tarikishaq@hotmail.com>"]
edition = "2018"
description = "My first crate!"
license = "MIT OR Apache-2.0"

[dependencies]

rand = "0.3.14"
